@startuml C4Context
!include libs\C4_Context.puml

title
    <b>Система сбора и анализа списков поступающих</b>
    <i>Context diagram</i>
end title

Person(user, "Приёмная комиссия")

System(system, "Агрегатор списков заявлений", "Имеет веб-интерфейс. Получает данные с сайтов вузов.")
System_Ext(universities_system, "Сайты вузов", "Содержат конкурсные списки.")

Rel(user, system, "Просматривает списки")
Rel(system, universities_system, "Получает списки")

@enduml